
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package backend.generacionHtml;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 21;
  public static final int AND = 10;
  public static final int MENOR = 25;
  public static final int PARENTESIS_ABIERTO = 28;
  public static final int ELSE = 14;
  public static final int IGUAL = 27;
  public static final int OR = 11;
  public static final int THEN = 13;
  public static final int WHILE = 15;
  public static final int END = 19;
  public static final int CORCHETE_CERRADO = 33;
  public static final int TRUE = 8;
  public static final int IF = 12;
  public static final int POR = 22;
  public static final int DOS_PUNTOS = 26;
  public static final int BEGIN = 18;
  public static final int PARENTESIS_CERRADO = 29;
  public static final int BOOLEAN = 6;
  public static final int COMA = 30;
  public static final int STRING = 7;
  public static final int MAYOR = 24;
  public static final int EOF = 0;
  public static final int DIV = 23;
  public static final int FALSE = 9;
  public static final int error = 1;
  public static final int NUMERO = 2;
  public static final int IDENTIFICADOR = 4;
  public static final int PUNTO_COMA = 31;
  public static final int INTEGER = 5;
  public static final int FOR = 16;
  public static final int CORCHETE_ABIERTO = 32;
  public static final int TO = 17;
  public static final int MAS = 20;
  public static final int VAR = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUMERO",
  "VAR",
  "IDENTIFICADOR",
  "INTEGER",
  "BOOLEAN",
  "STRING",
  "TRUE",
  "FALSE",
  "AND",
  "OR",
  "IF",
  "THEN",
  "ELSE",
  "WHILE",
  "FOR",
  "TO",
  "BEGIN",
  "END",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "MAYOR",
  "MENOR",
  "DOS_PUNTOS",
  "IGUAL",
  "PARENTESIS_ABIERTO",
  "PARENTESIS_CERRADO",
  "COMA",
  "PUNTO_COMA",
  "CORCHETE_ABIERTO",
  "CORCHETE_CERRADO"
  };
}

