/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend.gui;

import backend.errores.ManejadorDeErrores;
import javax.swing.JOptionPane;

/**
 *
 * @author jesfrin
 */
public class ErroresJDialog extends javax.swing.JDialog {
    
    private ElementosNavegadorPanel panel;
    private ManejadorDeErrores man;
    
    /**
     * Creates new form ErroresJDialog
     */
    public ErroresJDialog(java.awt.Frame parent, boolean modal,ElementosNavegadorPanel panel,ManejadorDeErrores man) {
        super(parent, modal);
        initComponents();
        this.panel=panel;
        this.man=man;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        formatoComboBox1 = new javax.swing.JComboBox<>();
        TipoDeSalidaParaError = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        formatoComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PorError", "PorTipoDeError", "Ninguno" }));

        TipoDeSalidaParaError.setText("Aceptar");
        TipoDeSalidaParaError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoDeSalidaParaErrorActionPerformed(evt);
            }
        });

        jLabel1.setText("El analisis concluyo con errores seleccione el formato de salida:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(formatoComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(TipoDeSalidaParaError)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formatoComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TipoDeSalidaParaError))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TipoDeSalidaParaErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoDeSalidaParaErrorActionPerformed
        int posicion=this.formatoComboBox1.getSelectedIndex();
        switch (posicion) {
            case 0:
                this.man.generarListadoDeErrores();
                JOptionPane.showMessageDialog(this,"Salida generada");
                break;
            case 1:
                this.man.generarListadoPorTipo();
                JOptionPane.showMessageDialog(this,"Salida generada");
                break;
            default:
                JOptionPane.showMessageDialog(this, "No se ha generado la salida");
                break;
        }
        this.dispose();
    }//GEN-LAST:event_TipoDeSalidaParaErrorActionPerformed

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TipoDeSalidaParaError;
    private javax.swing.JComboBox<String> formatoComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
