/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend.gui;

/**
 *
 * @author jesfrin
 */
public class NavegadorFrame extends javax.swing.JFrame {

    private int numeroDePestana;
    /**
     * Creates new form NavegadorFrame
     */
    public NavegadorFrame() {
        initComponents();
        this.numeroDePestana=1;
        contenedorTabbedPane1.add("Pestana"+numeroDePestana,new ElementosNavegadorPanel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedorTabbedPane1 = new javax.swing.JTabbedPane();
        cerrarPestanaButton = new javax.swing.JButton();
        nuevaPestanaButton = new javax.swing.JButton();
        analizarTodosButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        abrirArchivoMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cerrarPestanaButton.setText("Cerrar");
        cerrarPestanaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarPestanaButtonActionPerformed(evt);
            }
        });

        nuevaPestanaButton.setText("Nuevo");
        nuevaPestanaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaPestanaButtonActionPerformed(evt);
            }
        });

        analizarTodosButton.setText("Analizar todos");

        jMenu1.setText("Archivo");

        abrirArchivoMenuItem.setText("Abrir");
        abrirArchivoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirArchivoMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(abrirArchivoMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contenedorTabbedPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(1069, Short.MAX_VALUE)
                .addComponent(nuevaPestanaButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cerrarPestanaButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(analizarTodosButton)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cerrarPestanaButton)
                    .addComponent(nuevaPestanaButton)
                    .addComponent(analizarTodosButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(contenedorTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abrirArchivoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirArchivoMenuItemActionPerformed
        
    }//GEN-LAST:event_abrirArchivoMenuItemActionPerformed

    private void nuevaPestanaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaPestanaButtonActionPerformed
        numeroDePestana++;
        ElementosNavegadorPanel elemento = new ElementosNavegadorPanel();
        this.contenedorTabbedPane1.add("Pestana"+numeroDePestana,elemento);
        this.contenedorTabbedPane1.setSelectedComponent(elemento);
    }//GEN-LAST:event_nuevaPestanaButtonActionPerformed

    private void cerrarPestanaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarPestanaButtonActionPerformed
        this.contenedorTabbedPane1.remove(this.contenedorTabbedPane1.getSelectedComponent());
    }//GEN-LAST:event_cerrarPestanaButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem abrirArchivoMenuItem;
    private javax.swing.JButton analizarTodosButton;
    private javax.swing.JButton cerrarPestanaButton;
    private javax.swing.JTabbedPane contenedorTabbedPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton nuevaPestanaButton;
    // End of variables declaration//GEN-END:variables
}
